name: UsefulCommands
main: org.noip.evan1026.UsefulCommands
version: 1.0

commands:
    alias:
        description: Aliases a command.
        permission: evan1026.commands.alias
        usage: /<command> <aliasName> <commandName> <commandArgs>
    removeAlias:
        description: Removes an alias.
        permission: evan1026.commands.removeAlias
        usage: /<command> <aliasName>
    aliasList:
        description: Lists all existing aliases.
        permission: evan1026.commands.aliasList
        usage: /<command>
    playerInfo:
        description: Prints out information on a given player. Defaults to the sender if no player is given.
        permission: evan1026.commands.playerInfo
        usage: /<command> [player]
        
permissions:
    evan1026.commands.alias:
        description: Gives access to the /alias command.
        default: true
    evan1026.commands.removeAlias:
        description: Gives access to the /removeAlias command.
        default: op
    evan1026.commands.aliasList:
        description: Gives access to the /aliasList command.
        default: true
    evan1026.commands.playerInfo:
        description: Gives access to the /playerInfo command.
        default: op
        